apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;

    events {
      worker_connections  10240;
    }

    stream {
      server {
        listen 30009;
        proxy_connect_timeout 30s;
        proxy_socket_keepalive on;
        proxy_pass postgres-svc.postgres.svc.cluster.local:5432;
      }
    }